django_social_site/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, ScoreBoardView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('score_board/', ScoreBoardView.as_view(), name='score_board'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

groups/urls.py
from django.urls import path, include
from .views import (GroupCreateView, GroupDetailView, GroupDeleteView,
                        GroupUpdateView, GroupListView, MyGroupListView,
                        GroupJoinView, GroupLeaveView)

app_name = "groups"

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),
    path('mygroups/', MyGroupListView.as_view(), name='my_group_list'), #not used
    path('<slug:slug>/detail/', GroupDetailView.as_view(), name='group_detail'),
    path('<slug:slug>/delete/', GroupDeleteView.as_view(), name='group_delete'),
    path('new/', GroupCreateView.as_view(), name='group_create'),
    path('<slug:slug>/edit/', GroupUpdateView.as_view(), name='group_edit'),
    path('<slug:slug>/join/', GroupJoinView.as_view(), name='group_join'),
    path('<slug:slug>/leave/', GroupLeaveView.as_view(), name='group_leave'),
]

posts/urls.py
from django.urls import path, include
from .views import (PostCreateView, PostDeleteView, PostUpdateView, PostVoteView,
                    PostRemoveVoteView)

app_name = "posts"

urlpatterns = [
    path('<slug:group>/new/', PostCreateView.as_view(), name='post_create'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('<pk>/vote/', PostVoteView.as_view(), name='post_vote'),
    path('<pk>/remove_vote/', PostRemoveVoteView.as_view(), name='post_remove_vote'),
]

groups/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length = 200, unique = True)
    slug = models.CharField(max_length = 200)
    description = models.TextField(max_length = 1000)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = "own_groups", on_delete=models.CASCADE)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through = "GroupMembership")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)  # Call the "real" save() method.

    def get_absolute_url(self):
        return reverse('groups:group_detail', kwargs={'slug': self.slug})


class GroupMembership(models.Model):
    """
    Intermediary model that connects User and Group
    """
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    person = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("group", "person")

    def __str__(self):
        return self.person.username + " is a member of " + self.group.name

groups/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import Group, GroupMembership
# Create your views here.

class GroupListView(ListView):
    model = Group

class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    fields = ["name", "description"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save() #we need to save a group before assigning memebers via M2M
        form.instance.members.add(self.request.user)
        return super().form_valid(form)

class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    fields = ["name", "description"]

    def post(self, request, *args, **kwargs):
        """
        Incapsulate ownership verification. Only group owner can edit the group.
        """
        self.object = self.get_object()
        if self.request.user == self.object.owner:
            return super().post(request, *args, **kwargs)
        else:
            messages.warning(request, 'You cannot edit someone elses group')
            return redirect(self.request.path)

class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:group_list')

    def post(self, request, *args, **kwargs):
        """
        Incapsulate ownership verification. Only group owner can delete the group.
        """
        self.object = self.get_object()
        if self.request.user == self.object.owner:
            return super().post(request, *args, **kwargs)
        else:
            messages.warning(request, 'You cannot delete someone elses group')
            return redirect(self.request.path)

class GroupDetailView(DetailView):
    model = Group

class MyGroupListView(ListView):
    """
    This class is used as parent for HomePage View.
    TODO: move this class to main + remove my_group_list template and url.
    """
    template_name = "my_group_list.html"
    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Group.objects.filter(members = self.request.user)
        else:
            return None

class GroupJoinView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        group = Group.objects.get(slug = kwargs["slug"])
        person = self.request.user
        try:
            membership = GroupMembership.objects.create(group=group, person=person)
            membership.save()
        except:
            messages.warning(request, 'You cannot join this group because you are already its member')
        return redirect("groups:group_detail", slug=group.slug)

class GroupLeaveView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        group = Group.objects.get(slug = kwargs["slug"])
        person = self.request.user
        try:
            membership = GroupMembership.objects.get(group=group, person=person)
            membership.delete()
            messages.info(request, 'Group abandoned successfully')
        except:
            messages.warning(request, 'Leaving group failed')
        return redirect("groups:group_detail", slug=group.slug)

groups/templates/groups/_group.html
<div class="card group-item shadow-sm"
     onclick="location.href='{% url "groups:group_detail" group.slug %}'"
     style="cursor: pointer";>
  <div class="card-body">
    <h5 class="card-title group-card-title">{{group.name}}</h5>
    <p class="card-text">{{group.description|truncatechars:30}}</p>
    <span class="font-weight-lighter">Last activity: {{group.group_posts.all.0.created_at}}</span>
    <span class="font-weight-lighter float-right">Posts:{{group.group_posts.all.count}}</span>
  </div>
</div>

groups/templates/groups/group_confirm_delete.html
{% extends "common_base.html" %}

{% block base_top %}
<h1>Delete page</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Delete">
</form>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% endblock base_right %}

groups/templates/groups/group_detail.html
{% extends "common_base.html" %}

{% block base_top %}
<h1>{{object.name}}</h1>
<p>{{object.description}}</p>
{% endblock base_top %}

{% block base_bottom %}
<form class="shadow-sm" action="{% url "posts:post_create" group=object.slug %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="text">Add your post:</label>
    <div class="post-form">
      <textarea class="form-control post-textarea" name="text" placeholder="Enter your post here" rows="2" required></textarea>
      <div class="container">
        <div class="container post-form-toolbar d-flex justify-content-end">
          <button class="btn btn-link btn-font" type="submit" name="button">
            <svg width="1.2em" height="1.2em" viewBox="-4 1 16 16" class="bi bi-check" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
            </svg>
            Post
          </button>
        </div>
      </div>
    </div>
  </div>
</form>
<!-- LIST OF POSTS IN A GROUP -->
{% for post in object.group_posts.all %}
  {% include "posts/_post.html" with post=post %}
{% endfor %}
{% endblock base_bottom %}

{% block base_right %}
<div class="container">
  <h1>Welcome!</h1>
    {% if user.is_authenticated %}
      <!-- CHECK GROUP MEMBERSHIP -->
      {% if user in object.members.all %}
        <p>You are member of this group!</p>
        <a href="{% url "groups:group_leave" object.slug %}">
          <svg width="1em" height="1em" viewBox="0 1 16 16" class="bi bi-box-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
          Leave Group
        </a>
      {% else %}
        <p>You can join this group.</p>
        <a href="{% url "groups:group_join" object.slug %}">
          <svg width="1em" height="1em" viewBox="0 1 16 16" class="bi bi-box-arrow-in-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
            <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
          Join Group
        </a>
      {% endif %}
      <hr>
      <!-- CHECK GROUP OWNERSHIP -->
      {% if user == object.owner %}
        <p>You are owner of this group</p>
        <a href="{% url "groups:group_edit" object.slug %}">
          <svg width="0.8em" height="0.8em" viewBox="0 1 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
          Edit
        </a>
        <a href="{% url "groups:group_delete" object.slug %}">
          <svg width="1.2em" height="1.2em" viewBox="0 1 8 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
          Delete
        </a>
      {% endif %}

    {% endif %}
</div>
{% endblock base_right %}

groups/templates/groups/group_form.html
{% extends "common_base.html" %}
{% load bootstrap4 %}

{% block base_top %}
<h1>Welcome to a group form</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" name="" value="Submit">
</form>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% endblock base_right %}

groups/templates/groups/group_list.html
{% extends "common_base.html" %}

{% block base_top %}
  <h1>Group list page</h1>
  <p>Click on one of the groups from the list on the right to see its thread.</p>
  {% if user.is_authenticated %}
    <p>Click button bellow to start a new group:</p>
    <a class="btn btn-primary" href="{% url "groups:group_create" %}" role="button">New Group</a>
  {% endif %}
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}
  <h1>All Groups</h1>
  {% for group in group_list %}
  {% include "_group.html" with group=group %}
  {% endfor %}
{% endblock base_right %}

groups/templates/groups/my_group_list.html
{% extends "common_base.html" %}

{% block base_top %}
<h1>My own groups</h1>
{% for group in group_list %}
  <p>{{group}}</p>
{% endfor %}

{% endblock base_top %}