accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserCreateView, ProfileView

app_name = "accounts"

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name = "signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(), name = "logout"),
    path('my_profile/', ProfileView.as_view(), name='profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
]

django_social_site/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, ScoreBoardView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('score_board/', ScoreBoardView.as_view(), name='score_board'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

groups/urls.py
from django.urls import path, include
from .views import (GroupCreateView, GroupDetailView, GroupDeleteView,
                        GroupUpdateView, GroupListView, MyGroupListView,
                        GroupJoinView, GroupLeaveView)

app_name = "groups"

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),
    path('mygroups/', MyGroupListView.as_view(), name='my_group_list'), #not used
    path('<slug:slug>/detail/', GroupDetailView.as_view(), name='group_detail'),
    path('<slug:slug>/delete/', GroupDeleteView.as_view(), name='group_delete'),
    path('new/', GroupCreateView.as_view(), name='group_create'),
    path('<slug:slug>/edit/', GroupUpdateView.as_view(), name='group_edit'),
    path('<slug:slug>/join/', GroupJoinView.as_view(), name='group_join'),
    path('<slug:slug>/leave/', GroupLeaveView.as_view(), name='group_leave'),
]

posts/urls.py
from django.urls import path, include
from .views import (PostCreateView, PostDeleteView, PostUpdateView, PostVoteView,
                    PostRemoveVoteView)

app_name = "posts"

urlpatterns = [
    path('<slug:group>/new/', PostCreateView.as_view(), name='post_create'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('<pk>/vote/', PostVoteView.as_view(), name='post_vote'),
    path('<pk>/remove_vote/', PostRemoveVoteView.as_view(), name='post_remove_vote'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    karma = models.IntegerField(default=0)

    def update_karma(self, x):
        """
        Function that updates author karma x must be 1 or -1
        """
        self.karma += x
        return self.karma

    def __str__(self):
        return self.user.username

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flood Forum</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Cairo:wght@300;400;600;700;900&display=swap" rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css\master.css' %}">
  </head>
  <body>
      {% load bootstrap4 %}

      <!-- NavBar -->
      <nav class="navbar nav-custom navbar-expand-lg sticky-top navbar-light shadow">
        <a class="navbar-brand" href="/">FloodForum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url "groups:group_list" %}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "score_board" %}">ScoreBoard</a>
            </li>
          </ul>
        </div>

        <!-- NavBar right -->
        <div class="collapse navbar-collapse navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:profile" %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:logout" %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:signup" %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% bootstrap_messages %}
      
      {% block body %}
      {% endblock body %}
      <!-- Scripts -->
      <script src="{% static 'js\master.js' %}" charset="utf-8"></script>
      <!-- JS, Popper.js, and jQuery -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/common_base.html
{% extends "base.html" %}

{% block body %}
  <div class="container">
    <div class="row">
      <!-- LEFT BLOCK -->
      <div class="col-lg-7">
        <div class="container areas shadow" id="top-area">{% block base_top %}
          {% endblock base_top %}</div>
        <div class="container areas shadow" id="bottom-area">{% block base_bottom %}
          {% endblock base_bottom %}</div>
      </div>
      <!-- RIGHT BLOCK -->
      <div class="col-lg-5">
        <div class="container areas shadow" id="right-area">{% block base_right %}
          {% endblock base_right %}</div>
      </div>
    </div>
  </div>
{% endblock body %}

templates/home.html
{% extends "common_base.html" %}

{% block base_top %}
<div class="container">
  {% if user.is_authenticated %}
    <h1 class="display-4">Hello, <a href="{% url "accounts:profile" %}">{{user}}</a></h1>
    <p class="lead">Nice to see you here again!</p>
    <hr class="my-4">
    <p>Pick a group to start chatting:  </p>
    <a class="btn btn-primary btn" href="{% url "groups:group_list" %}" role="button">All Groups</a>
  {% else %}
    <h1 class="display-4">Welcome!</h1>
    <p class="lead">This is the best flood forum on the web.</p>
    <hr class="my-4">
    <p>You may use one of default user credentials:</p>
    <ol>
      <li>
        <ul>
          <li>Name: Jeffrey</li>
          <li>Pass: somepass</li>
        </ul>
      </li>
      <li>
        <ul>
          <li>Name: Dora</li>
          <li>Pass: somepass</li>
        </ul>
      </li>
    </ol>
    <a class="btn btn-primary" href="{% url "accounts:login" %}" role="button">Login</a>
    <hr>
    <p>Or you may register a new User and start chatting.</p>
    <a class="btn btn-secondary" href="{% url "accounts:signup" %}" role="button">Register</a>
  {% endif %}
</div>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% if user.is_authenticated %}
  <h2>List of your groups</h2>
      {% for group in group_list %}
      {% include "_group.html" with group=group %}
      {% endfor %}
  {% endif %}{% endblock base_right %}

templates/score_board.html
{% extends "common_base.html" %}

{% block base_top %}
<div class="container">
  <h1>Best Authors on Our Forum:</h1>
  <table class="table">
    <thead>
      <th style="width: 10%">Rank</th>
      <th>Name</th>
      <th class="d-flex justify-content-center">Karma</th>
    </thead>
    <tbody>
      {% for profile in userprofileinfo_list %}
      <tr>
        <td class="d-flex justify-content-center">{{forloop.counter}}</td>
        <td><a href="{% url "accounts:profile" profile.user %}">{{profile.user.username}}</a></td>
        <td class="d-flex justify-content-center">{{profile.karma}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% endblock base_right %}