accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserCreateView, ProfileView

app_name = "accounts"

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name = "signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(), name = "logout"),
    path('my_profile/', ProfileView.as_view(), name='profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
]

django_social_site/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, ScoreBoardView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('score_board/', ScoreBoardView.as_view(), name='score_board'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path, include
from .views import (PostCreateView, PostDeleteView, PostUpdateView, PostVoteView,
                    PostRemoveVoteView)

app_name = "posts"

urlpatterns = [
    path('<slug:group>/new/', PostCreateView.as_view(), name='post_create'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('<pk>/vote/', PostVoteView.as_view(), name='post_vote'),
    path('<pk>/remove_vote/', PostRemoveVoteView.as_view(), name='post_remove_vote'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from groups.models import Group, GroupMembership
from posts.mentions_helper import MentionsHandler as mentions
import markdown


class Post(models.Model):
    group = models.ForeignKey(Group, related_name = "group_posts", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = "my_posts", on_delete=models.CASCADE)
    text = models.TextField()
    text_html = models.TextField(default="")
    created_at = models.DateTimeField(default=timezone.now)
    voters = models.ManyToManyField(settings.AUTH_USER_MODEL, through = "PostVotes")
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        """
        Only members can create post in a group.
        """
        text_with_mentions = mentions.check_for_mentions(self.text)
        self.text_html = markdown.markdown(text_with_mentions)
        try:
            membership = GroupMembership.objects.filter(group = self.group).filter(person=self.author)
            if membership.exists():
                super().save(*args, **kwargs)
            else:
                print("could not save post because author does not belong to the group")
        except:
            print("some error occurred while querying GroupMembership table")

    def add_vote(self, vote):
        """
        Add vote to UpVotes if its value is 1 or to DownVotes if it is -1.
        """
        if vote == 1:
            self.up_votes += 1
            return self.up_votes
        elif vote == -1:
            self.down_votes += 1
            return self.down_votes
        else:
            print("wrong value")
            raise ValueError("wrong value")

    def remove_vote(self, vote):
        """
        Remove vote from UpVotes if its value is 1 or from DownVotes if it is -1.
        """
        if vote == 1:
            self.up_votes -= 1
            return self.up_votes
        elif vote == -1:
            self.down_votes -= 1
            return self.down_votes
        else:
            print("wrong value")
            raise ValueError("wrong value")

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_at']


class PostVotes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    voter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vote = models.IntegerField()

    class Meta:
        unique_together = ("post", "voter")

    def save(self, *args, **kwargs):
        """
        When PostVote is saved Post(up_votes/down_votes) and UserProfileInfo(karma)
        tables are updated.
        """
        self.post.add_vote(self.vote)
        self.post.save()
        self.post.author.userprofileinfo.update_karma(self.vote)
        self.post.author.userprofileinfo.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """
        When PostVote is deleted Post(up_votes/down_votes) and UserProfileInfo(karma)
        tables are updated.
        """
        self.post.remove_vote(self.vote)
        self.post.save()
        self.post.author.userprofileinfo.update_karma(0-(self.vote))
        self.post.author.userprofileinfo.save()
        super().delete(*args, **kwargs)

    @receiver(pre_delete)
    def delete_on_cascade(sender, *args, **kwargs):
        """
        If PostVote is delete due to Group/Post deletion this method will update
        karma for post author.
        """
        if sender == Post:
            post = kwargs["instance"]
            for post_vote in post.postvotes_set.all():
                vote = post_vote.vote
                post_vote.post.author.userprofileinfo.update_karma(0-(vote))
                post_vote.post.author.userprofileinfo.save()

    def __str__(self):
        return self.voter.username + " has voted " + str(self.vote) + " for " + self.post.text

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, PostVotes
from groups.models import Group, GroupMembership
from accounts.models import UserProfileInfo
from django.urls import reverse_lazy, reverse, resolve
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View

# Create your views here.
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["text"]

    def post(self, request, *args, **kwargs):
        """
        Only members of group can create posts.
        """
        person = self.request.user
        group = Group.objects.get(slug=self.kwargs["group"])
        try:
            membership = GroupMembership.objects.filter(group = group).filter(person=person)
            if membership.exists():
                return super().post(request, *args, **kwargs)
            else:
                messages.warning(request, '''Could not save post because you
                do not belong to the group. Please join group first''')
                return redirect(self.get_success_url())
        except:
            messages.warning(request, 'Somethin went wrong')
            return redirect(self.get_success_url())

    def get_success_url(self):
        group_slug = self.kwargs["group"]
        return reverse('groups:group_detail', kwargs={'slug': group_slug})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.group = Group.objects.get(slug = self.kwargs["group"])
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ["text"]

    def get_success_url(self):
        group_slug = self.object.group.slug
        return reverse('groups:group_detail', kwargs={'slug': group_slug})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post

    def post(self, request, *args, **kwargs):
        """
        Only authors can delete their posts.
        """
        self.object = self.get_object()
        if self.request.user == self.object.author:
            return super().post(request, *args, **kwargs)
        else:
            messages.warning(request, 'You cannot delete someone elses post')
            return redirect(self.request.path)

    def get_success_url(self):
        try:
            return self.request.POST["next"]
        except:
            group_slug = self.object.group.slug
            return reverse_lazy('groups:group_detail', kwargs={'slug': group_slug})

class PostVoteView(LoginRequiredMixin, View):
    """
    ViewClass that accepts post.pk as url kwarg and a "vote" value from POST request.
    Vote can be 1 or -1 integer. The vote is saved into PostVotes table, UpVotes(1)
    or DownVotes(-1) counter is incremented (using add_vote method), and karma for
    post author is updated by that value (1 or -1).
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(pk = kwargs["pk"])
        voter = self.request.user
        vote = int(self.request.POST["vote"])
        try:
            post_vote = PostVotes.objects.create(post=post, voter=voter, vote=vote)
        except:
            messages.warning(request, 'Something went wrong')
        return redirect("groups:group_detail", slug=post.group.slug)

class PostRemoveVoteView(LoginRequiredMixin, View):
    """
    ViewClass that accepts post.pk as url kwarg and remove user vote for that post.
    First, the Vote value is retrieved from PostVote table so user karma and post vote
    counter (via remove_vote method) can be updated. After that PostVote object
    is deleted.
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(pk = kwargs["pk"])
        voter = self.request.user
        try:
            post_vote = PostVotes.objects.get(post=post, voter=voter)
            post_vote.delete()
            messages.info(request, 'Vote removed successfully')
        except:
            messages.warning(request, 'something went wrong')
        return redirect("groups:group_detail", slug=post.group.slug)

posts/templates/posts/_post.html
{% load post_extras %}
<div class="post-item">
  <div class="card shadow-sm container">
    <div class="row">

      <!-- VOTING SECTION -->
      <div class="voting-section col-md-1 order-md-1 order-12 d-flex justify-content-center align-items-center">
        <div class="voting">
          {% if user in post.voters.all %}
            <form class="" action="{% url "posts:post_remove_vote" post.id %}" method="post">
          {% else %}
            <form class="" action="{% url "posts:post_vote" post.id %}" method="post">
          {% endif %}
          <div class="row">

            <div class="col">
              <button type="submit" class="btn btn-light btn-sm {% if post|vote_value:user == 1 %} active {% endif %}" name="vote" value=1 {% if post|vote_value:user == -1 %} disabled {% endif %}>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-up-fill" fill="green" xmlns="http://www.w3.org/2000/svg">
                  <path d="M7.247 4.86l-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                </svg>
              </button>
            </div>

            <div class="col d-flex justify-content-center align-items-center">
              {{post.up_votes|subtract:post.down_votes}}
            </div>

            <div class="col">
              <button type="submit" class="btn btn-light btn-sm {% if post|vote_value:user == -1 %} active {% endif %}" name="vote" value=-1 {% if post|vote_value:user == 1 %} disabled {% endif %}>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                  <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                </svg>
              </button>
            </div>
          </div>

            {% csrf_token %}
          </form>
        </div>
      </div>

      <!-- CARD BODY -->
      <div class="card-body col-md-11 order-1 order-md-12">
        <div class = "post-text">
          <p>
          {% autoescape off %}
          {% if post.text_html %}
          {{post.text_html}}
          {% else %}
          {{post}}
          {% endif %}
          {% endautoescape %}
          </p>
        </div>

<!--      </div>-->


        <!-- LEFT TOOLBAR -->
        <div class="d-inline toolbar-left">
          <span class="font-weight-lighter">{{post.created_at}}</span>
          <span class="font-weight-lighter">posted by</span>
          <span><a href="{% url "accounts:profile" post.author %}" class="card-link">
              {% if post.author.username == user.username %}
                You
              {% else %}
                @{{post.author}}
              {% endif %}
          </a></span>
          <span class="font-weight-lighter">(
              <svg width="0.8em" height="0.9em" viewBox="0 1 16 16" class="bi bi-trophy" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935zM3.504 1c.007.517.026 1.006.056 1.469.13 2.028.457 3.546.87 4.667C5.294 9.48 6.484 10 7 10a.5.5 0 0 1 .5.5v2.61a1 1 0 0 1-.757.97l-1.426.356a.5.5 0 0 0-.179.085L4.5 15h7l-.638-.479a.501.501 0 0 0-.18-.085l-1.425-.356a1 1 0 0 1-.757-.97V10.5A.5.5 0 0 1 9 10c.516 0 1.706-.52 2.57-2.864.413-1.12.74-2.64.87-4.667.03-.463.049-.952.056-1.469H3.504z"/>
              </svg>
            {{post.author.userprofileinfo.karma}})
          </span>
        </div>

        <!-- RIGHT TOOLBAR -->
        <div class="toolbar-right float-right">
          {% if post.author.username == user.username %}
            <!-- Edit button -->
            <span><a href="{% url "posts:post_edit" post.id %}" class="card-link">
              <svg width="0.8em" height="0.8em" viewBox="0 1 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
              </svg>
              Edit</a></span>
            <!-- Delete button -->
            <span>
              {% if my_profile %}
                <a href="{% url "posts:post_delete" post.id %}?next={% url "accounts:profile" %}" class="card-link">
              {% else %}
                <a href="{% url "posts:post_delete" post.id %}" class="card-link">
              {% endif %}
                <svg width="1.2em" height="1.2em" viewBox="0 1 8 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg>
                Delete
              </a>
            </span>
          {% endif %}
        </div>

      </div>
    </div>
  </div>
</div>

posts/templates/posts/my_post_list.html
{% extends "common_base.html" %}

{% block base_top %}
  <h1>My posts</h1>
  {% for post in post_list %}
  <p>{{post.text}} created: {{post.created_at}} author: {{post.author}}</p>
  {% endfor %}
  <h1>My grous</h1>
  {{group_list}}
{% endblock base_top %}

posts/templates/posts/post_confirm_delete.html
{% extends "common_base.html" %}

{% block base_top %}
  <p>Delete post page</p>
  <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
      {% endif %}
    <input type="submit" value="Confirm">
  </form>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% endblock base_right %}

posts/templates/posts/post_form.html
{% extends "common_base.html" %}
{% load bootstrap4 %}
{% block base_top %}
  <p>Post create/edit form</p>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <input type="submit" value="Update">
    {% endbuttons %}
  </form>
{% endblock base_top %}

{% block base_bottom %}{% endblock base_bottom %}

{% block base_right %}{% endblock base_right %}